baseURL = 'https://akwasiio.github.io/'
languageCode = 'en-us'
title = "Isaac Akwasi"
theme = 'etch'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true


[params]
headTitle = "Isaac Akwasi"
mainSections = ["posts"]
copyright = "Copyright © Isaac A. Oppong Jnr"
dark = "off"
highlight = true
extraCSSFiles = ["custom_table.css"]

[[params.socials]]
name = "Github"
link = "https://github.com/akwasiio"

[[params.socials]]
name = "Twitter"
link = "https://twitter.com/heyakwasi"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2
