baseURL = 'https://akwasiio.github.io/'
languageCode = 'en-us'
title = "Isaac's space"
theme = 'joway'

[params]
headTitle = "Isaac's space"
mainSections = ["posts"]

[[params.socials]]
name = "Github"
link = "https://github.com/akwasiio"

[[params.socials]]
name = "Twitter"
link = "https://twitter.com/heyakwasi"
