baseURL = 'https://akwasi-dev.github.io/'
languageCode = 'en-us'
title = "Isaac's space"

[author]
  name = "Isaac"
  homepage = "https://akwasi-dev.github.io/"

[[params.socials]]
name = "Github"
link = "https://github.com/akwasi-dev"

[[params.socials]]
name = "Twitter"
link = "https://twitter.com/heyakwasi"
